import { build } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { sourceFingerprint, treeHashes } from './desktop-inputs.mjs';
const require = createRequire(import.meta.url);
const { networkPolicy } = require('../desktop/policy.cjs');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const roomServiceUrl = process.env.VITE_ROOM_SERVICE_URL;
const turnCredentialsUrl = process.env.VITE_TURN_CREDENTIALS_URL;
if (!roomServiceUrl || !turnCredentialsUrl) throw new Error('Set VITE_ROOM_SERVICE_URL and VITE_TURN_CREDENTIALS_URL to the public production endpoints.');
networkPolicy({ roomServiceUrl, turnCredentialsUrl });
const pkg = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'));
const revision = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
const dirty = !!execFileSync('git', ['status', '--porcelain', '--untracked-files=normal'], { cwd: root, encoding: 'utf8' }).trim();
await build({ root, base: './', build: { outDir: 'dist-desktop', emptyOutDir: true, sourcemap: false } });
await fs.writeFile(path.join(root, 'desktop/build-config.json'), JSON.stringify({ version: pkg.version, revision, dirty, roomServiceUrl, turnCredentialsUrl, sourceHash: await sourceFingerprint(root), assets: await treeHashes(path.join(root, 'dist-desktop')) }, null, 2) + '\n');
console.log(`Desktop assets: v${pkg.version}, ${revision}${dirty ? ' (uncommitted working tree)' : ''}`);
