import { build } from 'vite';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { sourceFingerprint, treeHashes } from './desktop-inputs.mjs';
const require = createRequire(import.meta.url);
const { networkPolicy } = require('../desktop/policy.cjs');
const { steamAppId } = require('../desktop/platform.cjs');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const appId = steamAppId(process.env.STEAM_APP_ID);
networkPolicy({ transport: 'steam' });
const pkg = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'));
const revision = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
const dirty = !!execFileSync('git', ['status', '--porcelain', '--untracked-files=normal'], { cwd: root, encoding: 'utf8' }).trim();
await build({ root, mode: 'desktop', base: './', build: { outDir: 'dist-desktop', emptyOutDir: true, sourcemap: false } });
const shared = JSON.parse(await fs.readFile(path.join(root, 'dist-desktop/build-metadata.json'), 'utf8'));
await fs.writeFile(path.join(root, 'desktop/build-config.json'), JSON.stringify({ version: pkg.version, revision, dirty, transport: 'steam', steamAppId: appId,
  gameSourceHash: shared.gameSourceHash, sourceHash: await sourceFingerprint(root), assets: await treeHashes(path.join(root, 'dist-desktop')) }, null, 2) + '\n');
console.log(`Desktop assets: v${pkg.version}, ${revision}${dirty ? ' (uncommitted working tree)' : ''}`);
