const original = {
  bat: {
    name: "BAT",
    range: 94,
    damage: 35,
    force: 760,
    cooldown: 0.65,
    ammo: 8,
    kind: "melee",
  },
  sword: {
    name: "SWORD",
    range: 112,
    damage: 28,
    force: 520,
    cooldown: 0.38,
    ammo: 12,
    kind: "melee",
  },
  blaster: {
    name: "PISTOL",
    damage: 17,
    force: 350,
    cooldown: 0.25,
    ammo: 14,
    kind: "bullet",
    speed: 1300,
  },
  shotgun: {
    name: "SHOTGUN",
    damage: 10,
    force: 230,
    cooldown: 0.85,
    ammo: 5,
    kind: "pellet",
    speed: 1050,
    alt: {
      label: "DOUBLE SHOT",
      description: "Fire both shotgun barrels; uses two shells",
      count: 10,
      spread: 0.075,
      recoil: 420,
      cooldown: 1.25,
      ammoCost: 2,
    },
  },
  rocket: {
    name: "ROCKET LAUNCHER",
    damage: 64,
    force: 1100,
    cooldown: 1.1,
    ammo: 3,
    kind: "rocket",
    speed: 680,
    recoil: 360,
  },
  grenade: {
    name: "GRENADE",
    damage: 58,
    force: 1050,
    cooldown: 0.9,
    ammo: 4,
    kind: "grenade",
    speed: 1900,
    lift: 580,
    life: 2.8,
    recoil: 20,
  },
  minigun: {
    name: "MINIGUN",
    damage: 10,
    force: 190,
    cooldown: 0.075,
    ammo: 80,
    kind: "bullet",
    speed: 1650,
    recoil: 65,
    spread: 0.045,
  },
  railgun: {
    name: "RAILGUN",
    damage: 85,
    force: 1250,
    cooldown: 1.25,
    ammo: 4,
    kind: "rail",
    speed: 4600,
    recoil: 520,
  },
  plasma: {
    name: "PLASMA CANNON",
    damage: 48,
    force: 850,
    cooldown: 0.65,
    ammo: 7,
    kind: "plasma",
    speed: 850,
    recoil: 280,
    radius: 105,
    alt: {
      label: "CHARGED SHOT",
      description: "Fire a charged plasma orb; uses two rounds",
      damage: 70,
      force: 1100,
      radius: 150,
      bounces: 4,
      recoil: 440,
      speed: 720,
      cooldown: 1.2,
      ammoCost: 2,
      r: 15,
    },
  },
  barrage: {
    name: "TRIPLE ROCKET LAUNCHER",
    damage: 52,
    force: 1150,
    cooldown: 1.6,
    ammo: 3,
    kind: "rocket",
    speed: 780,
    recoil: 560,
    count: 3,
    radius: 180,
  },
};

export const COMBO = [
  {
    move: "punch",
    range: 82,
    damage: 25,
    force: 210,
    cooldown: 0.22,
    duration: 0.22,
    boost: 190,
    stun: 0.14,
  },
  {
    move: "kick",
    range: 103,
    damage: 32,
    force: 280,
    cooldown: 0.28,
    duration: 0.28,
    boost: 230,
    stun: 0.19,
  },
  {
    move: "spin",
    range: 112,
    damage: 43,
    force: 820,
    cooldown: 0.62,
    duration: 0.38,
    boost: 290,
    stun: 0.38,
  },
];
const additions = {
  nuke: {
    name: "NUCLEAR GRENADE",
    kind: "grenade",
    damage: 160,
    force: 1950,
    cooldown: 1.5,
    ammo: 1,
    speed: 1800,
    lift: 580,
    life: 2.8,
    radius: 620,
    recoil: 25,
    nuclear: true,
    rarity: "exotic",
    range: 2500,
    color: "#ffe77b",
    r: 12,
  },
  smg: {
    name: "SMG",
    kind: "bullet",
    damage: 9,
    force: 85,
    cooldown: 0.065,
    ammo: 60,
    speed: 1400,
    recoil: 12,
    spread: 0.14,
    rarity: "common",
    range: 700,
  },
  burst: {
    name: "BURST RIFLE",
    kind: "bullet",
    damage: 12,
    force: 110,
    cooldown: 0.3,
    ammo: 20,
    speed: 1750,
    count: 3,
    spread: 0.035,
    recoil: 45,
    rarity: "uncommon",
    range: 1100,
  },
  flame: {
    name: "FLAMETHROWER",
    kind: "flame",
    damage: 4,
    force: 25,
    cooldown: 0.055,
    ammo: 80,
    speed: 670,
    recoil: 3,
    spread: 0.23,
    life: 0.42,
    burn: 1.5,
    rarity: "uncommon",
    range: 270,
    color: "#ff9447",
  },
  frost: {
    name: "FREEZE RAY",
    kind: "frost",
    damage: 8,
    force: 55,
    cooldown: 0.12,
    ammo: 32,
    speed: 1250,
    recoil: 10,
    chill: 1.4,
    rarity: "uncommon",
    range: 700,
    color: "#a9f4ff",
  },
  ricochet: {
    name: "RICOCHET GUN",
    kind: "ricochet",
    damage: 24,
    force: 240,
    cooldown: 0.28,
    ammo: 16,
    speed: 1450,
    recoil: 35,
    bounces: 6,
    life: 3,
    rarity: "uncommon",
    range: 1100,
    color: "#ffb6ea",
  },
  saw: {
    name: "SAWBLADE LAUNCHER",
    kind: "saw",
    damage: 38,
    force: 320,
    cooldown: 0.65,
    ammo: 7,
    speed: 800,
    recoil: 65,
    bounces: 3,
    life: 3,
    rarity: "rare",
    range: 950,
    color: "#edf3f7",
  },
  tesla: {
    name: "TESLA GUN",
    kind: "tesla",
    damage: 34,
    force: 200,
    cooldown: 0.45,
    ammo: 10,
    speed: 2200,
    recoil: 30,
    rarity: "rare",
    range: 850,
    color: "#bbabff",
  },
  homing: {
    name: "HOMING LAUNCHER",
    kind: "rocket",
    damage: 56,
    force: 950,
    cooldown: 1.1,
    ammo: 4,
    speed: 530,
    recoil: 320,
    homing: true,
    radius: 150,
    rarity: "rare",
    range: 1400,
    color: "#ffb79c",
  },
  cluster: {
    name: "CLUSTER LAUNCHER",
    kind: "grenade",
    damage: 32,
    force: 700,
    cooldown: 1.3,
    ammo: 3,
    speed: 490,
    recoil: 260,
    cluster: true,
    radius: 120,
    rarity: "rare",
    range: 650,
    color: "#ffe796",
  },
  machinegun: {
    name: "HEAVY MACHINE GUN",
    kind: "bullet",
    damage: 18,
    force: 100,
    cooldown: 0.055,
    ammo: 100,
    speed: 2100,
    recoil: 0,
    spread: 0.018,
    proneOnly: true,
    rarity: "rare",
    range: 1600,
    color: "#f8c66e",
  },
  repulsor: {
    name: "REPULSOR",
    kind: "force",
    damage: 12,
    force: 1500,
    cooldown: 0.6,
    ammo: 6,
    speed: 1050,
    recoil: 380,
    life: 0.28,
    rarity: "rare",
    range: 280,
    color: "#8bffe0",
  },
  blackhole: {
    name: "BLACK HOLE GENERATOR",
    kind: "singularity",
    damage: 14,
    force: 0,
    cooldown: 1.7,
    ammo: 2,
    speed: 580,
    recoil: 300,
    life: 0.65,
    radius: 290,
    rarity: "exotic",
    range: 950,
    color: "#c6a1ff",
  },
};
const rarity = {
  bat: "common",
  sword: "common",
  blaster: "common",
  shotgun: "common",
  grenade: "uncommon",
  rocket: "uncommon",
  minigun: "uncommon",
  plasma: "rare",
  railgun: "rare",
  barrage: "exotic",
};
export const WEAPONS = Object.fromEntries(
  Object.entries({ ...original, ...additions }).map(([key, w]) => [
    key,
    { rarity: rarity[key] || w.rarity, ...w },
  ]),
);
export const RARITY_COLORS = {
  common: "#cfdbb3",
  uncommon: "#76dac4",
  rare: "#90bbff",
  exotic: "#daa1ff",
};
export function secondaryAction(player) {
  if (!player?.alive) return null;
  return player.weapon
    ? WEAPONS[player.weapon]?.alt || null
    : {
        label: "BLOCK",
        description: "Hold to block with fists; tap before impact to parry",
      };
}
export function firingRecoil(weapon, player) {
  if (weapon.proneOnly && player.prone && player.ground) return 0;
  return (
    weapon.recoil ??
    (weapon.kind === "pellet" ? 150 : weapon.kind === "melee" ? 0 : 40)
  );
}
// Applied to both initial map pickups and later drops; powerful fixed map spawns
// must not bypass rarity. Each tier's probability is independent of its size.
export function chooseWeapon(random = Math.random) {
  const roll = random();
  const tier =
    roll < 0.68
      ? "common"
      : roll < 0.93
        ? "uncommon"
        : roll < 0.99
          ? "rare"
          : "exotic";
  const pool = Object.keys(WEAPONS).filter((k) => WEAPONS[k].rarity === tier);
  return pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))];
}
export const PROJECTILE_KINDS = [
  ...new Set(
    Object.values(WEAPONS)
      .filter((w) => w.kind !== "melee")
      .map((w) => w.kind),
  ),
];
